const DELIVERY_STATUS_PENDING = 1;
const DELIVERY_STATUS_IN_PROGRESS = 2;
const DELIVERY_STATUS_COMPLETED = 3;
const DELIVERY_STATUS_CANCELLED = 4;

export const DELIVERY_STATUSES = {
    DELIVERY_STATUS_PENDING,
    DELIVERY_STATUS_IN_PROGRESS,
    DELIVERY_STATUS_COMPLETED,
    DELIVERY_STATUS_CANCELLED,
};

export const DELIVERY_STATUS_LABELS = {
    [DELIVERY_STATUS_PENDING]: 'Pending',
    [DELIVERY_STATUS_IN_PROGRESS]: 'Dalam Proses',
    [DELIVERY_STATUS_COMPLETED]: 'Selesai',
    [DELIVERY_STATUS_CANCELLED]: 'Dibatalkan',
};

export const DELIVERY_STATUS_COLORS = {
    [DELIVERY_STATUS_PENDING]: 'bg-yellow-100 text-yellow-800',
    [DELIVERY_STATUS_IN_PROGRESS]: 'bg-blue-100 text-blue-800',
    [DELIVERY_STATUS_COMPLETED]: 'bg-green-100 text-green-800',
    [DELIVERY_STATUS_CANCELLED]: 'bg-red-100 text-red-800',
};
